GET http://localhost:8001/users
###
PATCH http://localhost:8001/groups/addMember/6582541933e52289810a55a7
Content-Type: application/json

{
    "userEmail": "user3@gmail.com"
}
###

Get http://localhost:8001/groups/6578be5e7fcdb70a4ac2f6da
###

PATCH http://localhost:8001/expenses/6578bebb7fcdb70a4ac2f6e1
Content-Type: application/json

{
    "sender":"6578bcca5e31dd5accac326e",
    "title": "expenseAll4",
    "amount": 2000
}
###
POST http://localhost:8001/users
Content-Type: application/json

{
    "name": "Lizzie",
    "email": "sample5@gmail.com",
    "_password": "passwordCHECK"
}
###
GET http://localhost:8001/logout

###
POST http://localhost:8001/expenses
Content-Type: application/json

{
    "title" : "expenseAll5Yesgroupownedby2" ,
    "imageSrc": "/ss/receipt.png",
    "creator": "6578bcbc5e31dd5accac3262",
    "group":"6578be5e7fcdb70a4ac2f6da",
    "totalAmount": 2000,
    "distributions":[
        {
            "lendingUser": "6578bb26702b1194da19864d",
            "amount": 100,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bcc55e31dd5accac326a",
            "amount": 400,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bcca5e31dd5accac326e",
            "amount": 200,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bd621454d2d3bba288e5",
            "amount": 300,
            "title" : "expenseAll5Nogroupownedby2" 
        }
    ],
    "userIds":[
        "6578bb26702b1194da19864d",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]
}


###
POST http://localhost:8001/groups
Content-Type: application/json

{
    "groupName" : "groupAll5" ,
    "creator": "6578bb26702b1194da19864d",
    "userIds":[
        "6578bb26702b1194da19864d",
        "6578bcbc5e31dd5accac3262",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]
}
###
PATCH http://localhost:8001/expenses/payment/6581d2b958f61e13db4f83a7
Content-Type: application/json

{
    "sender" : "6578bcbc5e31dd5accac3262" ,
    "title": "getbwk8000",
    "amount": 2000
}
###
"userIds":[
        "6578bb26702b1194da19864d",
        "6578bcbc5e31dd5accac3262",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]

###
DELETE http://localhost:8001/groups/6580a064c3da4af84ac89b3d

