GET http://localhost:8001/groups/6580a248895da28b72c93e58
###
GET http://localhost:8001/expenses/groupId/6578be5e7fcdb70a4ac2f6da
###

DELETE http://localhost:8001/expenses/657b617ce7c1de06003d01d5
###

PATCH http://localhost:8001/expenses/6578bebb7fcdb70a4ac2f6e1
Content-Type: application/json

{
    "sender":"6578bcca5e31dd5accac326e",
    "title": "expenseAll4",
    "amount": 2000
}
###
POST http://localhost:8001/users/login
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@gmail.com",
    "_password": "password"
}
###
GET http://localhost:8001/logout

###
POST http://localhost:8001/expenses
Content-Type: application/json

{
    "title" : "expenseAll5Yesgroupownedby2" ,
    "imageSrc": "/ss/receipt.png",
    "creator": "6578bcbc5e31dd5accac3262",
    "group":"6578be5e7fcdb70a4ac2f6da",
    "totalAmount": 2000,
    "distributions":[
        {
            "lendingUser": "6578bb26702b1194da19864d",
            "amount": 100,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bcc55e31dd5accac326a",
            "amount": 400,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bcca5e31dd5accac326e",
            "amount": 200,
            "title" : "expenseAll5Nogroupownedby2" 
        },
        {
            "lendingUser": "6578bd621454d2d3bba288e5",
            "amount": 300,
            "title" : "expenseAll5Nogroupownedby2" 
        }
    ],
    "userIds":[
        "6578bb26702b1194da19864d",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]
}


###
###
POST http://localhost:8001/groups
Content-Type: application/json

{
    "groupName" : "groupAll5" ,
    "creator": "6578bb26702b1194da19864d",
    "userIds":[
        "6578bb26702b1194da19864d",
        "6578bcbc5e31dd5accac3262",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]
}
###
"userIds":[
        "6578bb26702b1194da19864d",
        "6578bcbc5e31dd5accac3262",
        "6578bcc55e31dd5accac326a",
        "6578bcca5e31dd5accac326e",
        "6578bd621454d2d3bba288e5"
    ]
